Repository hyprutils/hyprwall, pull requests merged in 2024-10, with the labels that each got.

#2 code optimization
  .github/preview.png
  Cargo.lock
  Cargo.toml
  readme.md
  src/gui.rs
  src/main.rs
Labels: enhancement

#3 better error handling & code readibility
  src/gui.rs
  src/main.rs
Labels: enhancement

#4 add a check to see if hyprpaper is running if not then start it
  src/main.rs
Labels: bug

#5 readme updates
  readme.md
Labels: documentation

#7 implement filename/ext tooltips
  src/gui.rs
Labels: enhancement

#8 implement Multiple backends
  readme.md
  src/gui.rs
  src/main.rs
Labels: enhancement

#9 popups
  src/gui.rs
  src/main.rs
Labels: enhancement

#10 cleanup mem & use true async to prevent freezing when execing cmds
  Cargo.lock
  Cargo.toml
  readme.md
  src/gui.rs
  src/main.rs
Labels: enhancement

#11 fix error messages not showing up
  src/main.rs
Labels: bug

#12 implement cli arguments
  Cargo.lock
  Cargo.toml
  readme.md
  src/gui.rs
  src/main.rs
Labels: enhancement

#14 add a logo by @Sebaguardian
  .github/hyprwall.png
  hyprwall.desktop
  hyprwall.svg
  readme.md
  src/gui.rs
Labels: documentation, enhancement

#15 add basic refresh functionality
  .github/preview.png
  src/gui.rs
Labels: enhancement

#17 add --random cli arg
  src/gui.rs
  src/main.rs
Labels: enhancement

#18 Add new cli args
  src/gui.rs
  src/main.rs
Labels: enhancement

#19 fix: hyprpaper not starting without `hyprpaper.conf`
  readme.md
  src/main.rs
Labels: bug

#20 docs: add a manpage
  man/hyprwall.1
Labels: enhancement

#21 feat: add a `--copyright` command
  man/hyprwall.1
  src/main.rs
Labels: enhancement

#22 v0.1.5
  Cargo.lock
  Cargo.toml
Labels: enhancement

#23 Implement Gif support
  readme.md
  src/gui.rs
Labels: enhancement

#24 add onto the benefits section
  readme.md
Labels: documentation

#25 Implement Search functionality
  readme.md
  src/gui.rs
Labels: enhancement

#26 Implement right-click preview windows
  readme.md
  src/gui.rs
Labels: enhancement

#27 v0.1.6
  Cargo.lock
  Cargo.toml
Labels: enhancement

#29 upd preview
  .github/preview.png
Labels: documentation

#31 docs: more release labels
  .github/release.yml
Labels: documentation

#34 fix: application_id naming
  src/main.rs
Labels: bug

#40 v0.1.7
  Cargo.lock
  Cargo.toml
Labels: skip-changelog
