Repository hyprutils/hyprwall, pull requests merged in 2024-11, with the labels that each got.

#43 fix incorrect definition
  readme.md
Labels: documentation

#44 use relative path
  src/gui.rs
  src/main.rs
Labels: enhancement, gui, refactor

#45 v0.1.8
  Cargo.lock
  Cargo.toml
Labels: enhancement

#47 fix incorrect repo
  Cargo.toml
Labels: backend, refactor

#49 resolve path in args
  src/main.rs
Labels: backend, refactor

#51 fix: HashMap issues
  src/gui.rs
Labels: backend, performance, refactor

#56 docs: add the Grind badge & move stuff around
  readme.md
Labels: documentation
